import json
import os
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional


def _extract_json(text: str) -> Dict[str, Any]:
    """
    Extract a JSON object from Codex stdout.

    Preferred:
        Pure JSON.

    Fallback:
        Extract the first {...} block from stdout.

    Raises:
        ValueError if no JSON object is found.
    """
    text = (text or "").strip()

    if not text:
        raise ValueError("Empty Codex stdout. No JSON object found.")

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    start = text.find("{")
    end = text.rfind("}")

    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"No JSON object found in Codex output:\n{text[:2000]}")

    candidate = text[start : end + 1]
    return json.loads(candidate)


def _safe_read_text(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return None
    except Exception:
        return None


def read_generated_project(workspace: Path) -> Dict[str, Any]:
    """
    Read files generated by Codex CLI from a workspace directory
    and convert them into the bridge's expected format.

    Returns:
        {
            "project_name": "...",
            "files": {
                "relative/path": "file content"
            },
            "summary": "...",
            "assumptions": [...]
        }
    """
    workspace = workspace.resolve()

    skip_dirs = {
        ".git",
        ".venv",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".codex",
        "node_modules",
    }

    skip_files = {
        "prompt.txt",
        "codex_stdout.txt",
        "codex_stderr.txt",
    }

    allowed_suffixes = {
        ".py",
        ".md",
        ".json",
        ".txt",
        ".yml",
        ".yaml",
        ".toml",
    }

    files: Dict[str, str] = {}

    for path in workspace.rglob("*"):
        if not path.is_file():
            continue

        rel = path.relative_to(workspace)

        if any(part in skip_dirs for part in rel.parts):
            continue

        if path.name in skip_files:
            continue

        if path.suffix and path.suffix not in allowed_suffixes:
            continue

        content = _safe_read_text(path)
        if content is None:
            continue

        files[rel.as_posix()] = content

    return {
        "project_name": workspace.name,
        "files": files,
        "summary": f"Collected {len(files)} generated files from Codex CLI workspace.",
        "assumptions": [
            "Codex CLI was executed in a local workspace.",
            "The bridge collected generated source, test, example, and report files from that workspace.",
        ],
    }


def _prepare_workspace() -> Path:
    """
    Create or reset Codex workspace.

    Default:
        ./debug_codex_workspace

    You can override it with:
        CODEX_WORKSPACE=./some_workspace
    """
    workspace = Path(os.getenv("CODEX_WORKSPACE", "./debug_codex_workspace")).resolve()

    reset = os.getenv("CODEX_RESET_WORKSPACE", "1") == "1"

    if workspace.exists() and reset:
        shutil.rmtree(workspace)

    workspace.mkdir(parents=True, exist_ok=True)
    return workspace


def _run_codex_cli(prompt: str, workspace: Path) -> subprocess.CompletedProcess:
    """
    Run local Codex CLI.

    Default command:
        codex exec -m gpt-5.4 --full-auto -

    You can override with:
        CODEX_CMD='codex exec -m gpt-5.4 --full-auto -'
    """
    cmd = os.getenv("CODEX_CMD", "codex exec -m gpt-5.4 --full-auto -")
    timeout = int(os.getenv("CODEX_TIMEOUT", "600"))

    cmd_parts = shlex.split(cmd)

    print("=== CODEX WORKSPACE ===")
    print(str(workspace))
    print("=== CODEX CMD ===")
    print(cmd_parts)
    print("=== CODEX PROMPT HEAD ===")
    print(prompt[:2000])

    proc = subprocess.run(
        cmd_parts,
        input=prompt,
        cwd=workspace,
        text=True,
        capture_output=True,
        timeout=timeout,
    )

    stdout_path = workspace / "codex_stdout.txt"
    stderr_path = workspace / "codex_stderr.txt"
    stdout_path.write_text(proc.stdout or "", encoding="utf-8")
    stderr_path.write_text(proc.stderr or "", encoding="utf-8")

    print("=== CODEX RETURN CODE ===")
    print(proc.returncode)
    print("=== CODEX STDOUT HEAD ===")
    print((proc.stdout or "")[:4000])
    print("=== CODEX STDERR HEAD ===")
    print((proc.stderr or "")[:4000])

    return proc


def call_codex_json(prompt: str) -> Dict[str, Any]:
    """
    Main entry used by app.py.

    It supports two Codex CLI behaviors:

    Case 1:
        Codex returns valid JSON to stdout.
        This is preferred for /repair_project and also supported for /generate_project.

    Case 2:
        Codex writes project files into the workspace but does not return JSON.
        The client reads the workspace and wraps files as:
            {"project_name": ..., "files": ...}

    Environment variables:
        CODEX_CMD:
            Default: codex exec -m gpt-5.4 --full-auto -

        CODEX_TIMEOUT:
            Default: 600

        CODEX_WORKSPACE:
            Default: ./debug_codex_workspace

        CODEX_RESET_WORKSPACE:
            Default: 1
            If 1, clear workspace before each Codex call.
    """
    workspace = _prepare_workspace()

    prompt_path = workspace / "prompt.txt"
    prompt_path.write_text(prompt, encoding="utf-8")

    proc = _run_codex_cli(prompt=prompt, workspace=workspace)

    if proc.returncode != 0:
        raise RuntimeError(
            "Codex CLI failed.\n"
            f"Return code: {proc.returncode}\n\n"
            f"STDERR:\n{proc.stderr}\n\n"
            f"STDOUT:\n{proc.stdout}\n"
        )

    # 1. First try JSON mode.
    try:
        parsed = _extract_json(proc.stdout)

        if not isinstance(parsed, dict):
            raise ValueError("Parsed Codex output is not a JSON object.")

        # Normal expected generate_project result:
        # {
        #   "project_name": "...",
        #   "files": {...},
        #   "summary": "...",
        #   "assumptions": [...]
        # }
        #
        # Normal expected repair_project result:
        # {
        #   "modified_files": {...},
        #   "root_cause": "...",
        #   "repair_summary": "..."
        # }
        return parsed

    except Exception as json_error:
        print("=== JSON PARSE FAILED; FALLING BACK TO FILE COLLECTION ===")
        print(str(json_error))

    # 2. Fallback: file-generation mode.
    result = read_generated_project(workspace)

    generated_files = result.get("files", {})

    if not generated_files:
        raise RuntimeError(
            "Codex CLI completed, but it neither returned valid JSON nor generated files.\n\n"
            "Possible reasons:\n"
            "1. Codex CLI is waiting for interaction or approval.\n"
            "2. CODEX_CMD is incorrect.\n"
            "3. The prompt asks Codex to explain instead of writing files.\n"
            "4. Codex wrote files outside the workspace.\n\n"
            f"Workspace: {workspace}\n"
            f"STDOUT:\n{proc.stdout}\n\n"
            f"STDERR:\n{proc.stderr}\n"
        )

    return result
